### ISSUE TITLE
proc-macro panic

### ISSUE THREAD

**Issue by cisaacson** [ct-austin/ifmt#5]
This is not a major showstopper but thought you should know.

I am using `iwriteln!` and if I just include a single `&str` the macro panics. Here is an example:

```
iwriteln!(&mut code, "}")?;
```

The error says `unmatched }`. 

Then I tried this:

```
iwriteln!(&mut code, "abc }")?;
```
Still got a panic, but not the same message.

I worked around it by doing this:

```
iwriteln!(&mut code, "}" "")?;
```

So it appears that a variable or another expression is always required. If that is intentional adding that to the doc would help.

Great job by the way, as you can see I am doing some code-gen, `ifmt` is going to make it pretty easy to do.

**Comment by ct-austin** [comment]
Can you post a full example to cause the error message you get for `iwriteln!(&mut code, "abc }")?;` and the error message? I'm getting the same error messages for both.

What's happening here is that versions 0.1 and 0.2 had a different syntax which requires literal braces to be escaped—`iprintln!("x = {x}, y = {y}, x + y = {x + y})");`—and version 0.3 still supports this syntax if you only pass in a single string, but it's no longer preferred. See [here](https://docs.rs/ifmt/0.3.0/ifmt/macro.iformat.html). Long-term I may remove support for the older syntax, but in the meantime I probably should note this particular gotcha in the documentation.

**Comment by cisaacson** [comment]
Here is another one that doesn't work:

The error is:
```
expected expressionrustc
owned_schema_generator.rs(392, 37): Error originated from macro here
```

In a version with longer var names it errors like this (different line number):
```
expected expressionrustc
owned_schema_generator.rs(384, 37): Error originated from macro here
```

The example is: 
```
let n = &"test".to_string();
let o = "o".to_string();
let s: String = iformat!("Option<{{", n "::" o "}}>");
```

Here is the other example you asked for:
```
proc-macro derive panicked
message: unmatched }
```

```
let mut code = "".to_string();
let s: String = iwriteln!(&mut code, "abc }")?;
```

Hope that helps track it down. For the first error above I am just using `format!` as a work-around.

**Comment by ct-austin** [comment]
> ```rust
> let n = &"test".to_string();
> let o = "o".to_string();
> let s: String = iformat!("Option<{{", n "::" o "}}>");
> ```
There's a stray comma here, seems to work as intended if you change it to `iformat!("Option<{{" n "::" o "}}>");`? (Unless the output you want is `Option<{test::o}>` rather than `Option<{{test::o}}>` in which case it should just be `iformat!("Option<{" n "::" o "}>");`, braces only need to be escaped if you pass a single string literal, otherwise they don't carry any special meaning)

> Here is the other example you asked for:
> ```
> proc-macro derive panicked
> message: unmatched }
> ```
> 
> ```rust
> let mut code = "".to_string();
> let s: String = iwriteln!(&mut code, "abc }")?;
> ```

That's the expected error message, and the same one as the other example you gave in the original post?

**Comment by cisaacson** [comment]
Thanks on the first example, now I understand. If a single string, you need to escape the single `}` char.

How about this one? It is actually what I need:

```
let n = &"test".to_string();
let o = "o".to_string();
let s: String = iformat!("Option<" n "::" o ">");
```

```
invalid format string: expected `'}'` but string was terminated
if you intended to print `{`, you can escape it using `{{`rustc
owned_schema_generator.rs(403, 21): because of this opening brace
owned_schema_generator.rs(403, 47): Error originated from macro here
```
There are no `{` chars at all, so the error seems wrong. 

Thanks for the quick response, let me know if I'm doing something incorrectly.

**Comment by ct-austin** [comment]
That is a bug, damn.

The issue is that `iprintln!("Option<" a "::" b ">")` gets expanded to `println!("Option<{:}::{:}>", a, b);` and the built-in formatter macro interprets the `}` in `{:}>` as part of the format spec rather than as a closing brace, expecting something like `println!("{:}>5}", x);`. I'll have to update the expansion to special-case on an empty format spec and expand to `{}` rather than `{:}` (this works because the fill character is always the first character in the format spec, so ambiguity should hopefully only be possible when empty).

**Comment by ct-austin** [comment]
Fixed.

**Comment by cisaacson** [comment]
Great! That was very fast. Let me know when it's published.

Really a great tool, it's saving me a lot of time and very easy to read the code. I'm a fan!

**Comment by cisaacson** [comment]
You may want to update the version in the README too to 0.3.1. Again thanks for the responsiveness.
