### ISSUE TITLE
Is in-literal style here to stay?

### ISSUE THREAD

**Issue by jgarvin** [ct-austin/ifmt#8]
The docs describe it as "old", and I'm not sure if I should take this to mean deprecated. It's still more convenient to not have to terminate and restart the string literal each time I want to print something, esp. if I am editing and changing my mind about where in the string I want to put my expressions.

**Comment by ct-austin** [comment]
My original intent was to remove it eventually unless enough people had a strong preference for the original syntax, though given the nature of the project I think it's more likely that the standard lib gets the feature before it gets to a stage where I'd actually be comfortable making that change.

But wrt your particular use case: what makes it easier to move around `{ foo + bar }` braces than `" foo + bar "` quotes? I chose the quote syntax in part because it's the same number of delimiter characters—although there is a minor catch which is that whitespace is no longer optional because of literal suffixes.

**Comment by jgarvin** [comment]
Say initially I have:

`"here foo {bar} buzz"`

And I change my mind and I want:

`"here {bar} foo buzz"`

I don't even pay attention to the delimiters. I just move stuff around inside the string. Now with the alternative syntax I would have started with:

`"here foo" {bar} "buzz"`

Now I'm forced to mess with the delimiters on both sides:

`"here" {bar} "foo buzz"`

I had to add a quote to here, add a quote to foo, and delete a quote from buzz (which technically I could have left so that I just had two string literals in a row but that would look odd).

In essence with the first style I just moved what I wanted moved, with the second style I move it and then adjust a bunch of quotes.

**Comment by ct-austin** [comment]
Your two examples aren't equivalent - the quote syntax is missing some spaces - but regardless of which one you meant I think you're doing more work than you need to (I'm assuming by "move" you mean "cut and paste") with the quote example.

Instead of selecting `"here foo " [bar] " buzz"` (space inside `[braces]` is your selection) and then pasting it `"here [bar] foo " "buzz"` and manually fixing up the quotes after the fact, you should select `"here foo[ " bar "] buzz"` and then paste it `"here[ "bar "] foo buzz`.

**Comment by jgarvin** [comment]
Not making the spaces mistake is another benefit of the first syntax ;)

You're right though it's possible to do with the wider selection. It's still a bit awkward for me, because I've gotten used to not copy and pasting single delimiters since it risks breaking structure and my editor has convenient bindings for copy and pasting the contents delimited sections like strings, parenthesized expressions etc. so I don't usually copy and paste something that straddles. Maybe I will get used to it, but my intuition is with the first style I'm "just" editing the string, and with the second style I'm consciously strategizing how not to break the delimeters in addition to making the edit I wanted.
